#!/bin/sh

mkdir -p /data/logs
DATETIME=`date +%Y-%m-%d:%H:%M:%S`
DATE=`date +%Y-%m-%d`

export PYTHONIOENCODING=utf-8
export LANG=zh_CN.UTF-8
export PYTHONPATH=/data/stock
export LC_CTYPE=zh_CN.UTF-8

echo "###################"$DATETIME"###################" >> /data/logs/evening_report.${DATE}.log
#尾盘选股报告（14:50执行）
/usr/local/bin/python3 /data/stock/jobs/evening_report_job.py >> /data/logs/evening_report.${DATE}.log
