#!/bin/sh

mkdir -p /data/logs
DATETIME=`date +%Y-%m-%d:%H:%M:%S`
DATE=`date +%Y-%m-%d`

export PYTHONIOENCODING=utf-8
export LANG=zh_CN.UTF-8
export PYTHONPATH=/data/stock
export LC_CTYPE=zh_CN.UTF-8

echo "###################"$DATETIME"###################" >> /data/logs/meishi_tech.${DATE}.log
#魅视科技式选股（8:30执行，分析前一交易日数据）
/usr/local/bin/python3 /data/stock/jobs/meishi_tech_job.py >> /data/logs/meishi_tech.${DATE}.log
